// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcoueErYig4qZgcgQWRZmhfvnA8zy9o5A',
    appId: '1:863828786417:web:17aded7df9fa98f69dfd50',
    messagingSenderId: '863828786417',
    projectId: 'software-engineering-pro-77f57',
    authDomain: 'software-engineering-pro-77f57.firebaseapp.com',
    storageBucket: 'software-engineering-pro-77f57.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoPR_UCSLy64oJJyqdCH8-FJTmpX8-N8o',
    appId: '1:863828786417:android:efda5cfafba70f6c9dfd50',
    messagingSenderId: '863828786417',
    projectId: 'software-engineering-pro-77f57',
    storageBucket: 'software-engineering-pro-77f57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxTnGGc3-PTrO4oPgxKM1itB4TJNTp0JE',
    appId: '1:863828786417:ios:200e41e3b666fa7b9dfd50',
    messagingSenderId: '863828786417',
    projectId: 'software-engineering-pro-77f57',
    storageBucket: 'software-engineering-pro-77f57.appspot.com',
    iosBundleId: 'com.example.softwareEngineeringProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxTnGGc3-PTrO4oPgxKM1itB4TJNTp0JE',
    appId: '1:863828786417:ios:7e8b09bdc654163d9dfd50',
    messagingSenderId: '863828786417',
    projectId: 'software-engineering-pro-77f57',
    storageBucket: 'software-engineering-pro-77f57.appspot.com',
    iosBundleId: 'com.example.softwareEngineeringProject.RunnerTests',
  );
}
